# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-3d0404e3-cee7-4eac-afe7-a7587b5ba487";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-3d0404e3-cee7-4eac-afe7-a7587b5ba487".device =
    "/dev/disk/by-uuid/3d0404e3-cee7-4eac-afe7-a7587b5ba487";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3B06-A2E9";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-dac4e371-be5c-4224-b2e1-e531f5affdc0"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
